"""add_backend_models

Revision ID: e5a793ec0653
Revises: c4a8b1d2e3f5
Create Date: 2026-06-19 23:56:05.330244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a793ec0653'
down_revision: Union[str, Sequence[str], None] = 'c4a8b1d2e3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_sku_demands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.String(length=255), nullable=False),
    sa.Column('p05_total', sa.Float(), nullable=False),
    sa.Column('p50_total', sa.Float(), nullable=False),
    sa.Column('p95_total', sa.Float(), nullable=False),
    sa.Column('days_to_stockout', sa.Float(), nullable=True),
    sa.Column('daily_forecasts_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_sku_demands_sku_id'), 'cached_sku_demands', ['sku_id'], unique=True)
    op.create_table('cached_supplier_risks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('shap_drivers_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_supplier_risks_supplier_id'), 'cached_supplier_risks', ['supplier_id'], unique=True)
    op.create_table('inventory_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.String(length=255), nullable=False),
    sa.Column('units_on_hand', sa.Integer(), nullable=False),
    sa.Column('units_in_transit', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_levels_sku_id'), 'inventory_levels', ['sku_id'], unique=True)
    op.create_table('model_training_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('log_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_training_jobs_model_name'), 'model_training_jobs', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_training_jobs_status'), 'model_training_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_training_jobs_status'), table_name='model_training_jobs')
    op.drop_index(op.f('ix_model_training_jobs_model_name'), table_name='model_training_jobs')
    op.drop_table('model_training_jobs')
    op.drop_index(op.f('ix_inventory_levels_sku_id'), table_name='inventory_levels')
    op.drop_table('inventory_levels')
    op.drop_index(op.f('ix_cached_supplier_risks_supplier_id'), table_name='cached_supplier_risks')
    op.drop_table('cached_supplier_risks')
    op.drop_index(op.f('ix_cached_sku_demands_sku_id'), table_name='cached_sku_demands')
    op.drop_table('cached_sku_demands')
    # ### end Alembic commands ###
